version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/liuyihua/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: lyh123456
    ports:
      - '3306:3306'
    networks:
      - common-network

  redis-container:
    image: redis
    volumes:
      - /Users/liuyihua/redis-data:/data
    ports:
      - '3739:3739'
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
